name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        if: runner.os == 'Linux'
        run: sudo apt -qq install libgtk-3-dev
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Build examples
        run: cd examples && zig build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Setup formatter
        run: |
          curl -Lo vzit https://github.com/ttytm/vzit/releases/latest/download/vzit-linux-amd64
          chmod +x vzit
          ./vzit --version
      - name: Verify formatting
        run: ./vzit --diff .
